logging:
    level:
        org:
            zalando:
                logbook: TRACE
        root: INFO
server:
    port: 9090
spring:
    batch:
        jdbc:
            initialize-schema: always
    datasource:
        driverClassName: org.postgresql.Driver
        password: ${POSTGRES_PASSWORD}
        url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
        username: ${POSTGRES_USER}
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQL10Dialect
                format_sql: true
    sql:
        init:
            mode: always
springbatch:
    resource: classpath*:prices/*_values.csv
